Global: # Global Multipliers
  Speed: 1
  Jump: 1
  Gravity: 1
  StaminaCost: 1

# Adding a '#' before text comments it out
# If the line starts with a '-', it's specifying a new item modifier.

# Here is a run down of how the configuration works:

#    The id specifies which item this should effect.
#    This id can either be the name of the item (i.e. Viper) or the number-based id (i.e. 1027).

# Every item id is followed by the modifiers. All modifiers are optional and are as follows:

#    Speed - A speed multiplier (i.e. 2 will make the player move twice as fast)
#    Jump - A jump multiplier (i.e. 5 will make the player jump five times higher)
#    Gravity - A gravity multiplier (i.e. 0.1 will make the player have very low gravity)
#    StaminaCost - A stamina cost multiplier (i.e. 0 will make the player use no stamina)

# Every item modifier has the optional property 'MustBeEquipped' (true/false).
# This property specifies whether or not the item must be equipped.

# By default (if not explicitly set), all clothing items, guns, melee weapons, tools,
# and clouds (umbrellas) must be equipped.

# You can uncomment (remove the '#') features below to add them to the Viper config

# The example with the Viper below will increase the player's speed, jump,
# and gravity two times when a Viper is equipped.

ItemModifiers:
- Id: Viper
  Speed: 2
  Jump: 2
  Gravity: 2
#  StaminaCost: 0.5
#  MustBeEquipped: false

- Id: Tracksuit Top
  Gravity: 0.5

- Id: Ace
  StaminaCost: 0
  MustBeEquipped: false