name: MovementModifier Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin Version'
        required: true

jobs:
  build:
    name: "GitHub Release"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: MovementModifier Release ${{ github.event.inputs.version }}
        draft: true
        prerelease: false
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Update versions
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" \"MovementModifier - OpenMod/MovementModifier - OpenMod.csproj\" \"MovementModifier - Rocket/MovementModifier - Rocket.csproj\""
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Install zip
      run: sudo apt-get install zip
      
    - name: Zip Rocket release artifacts
      run: |
        mkdir -p ./Rocket/Plugins ./Rocket/Libraries
        cd "./MovementModifier - Rocket/bin/Release/net461"
        mv MovementModifier.dll ../../../../Rocket/Plugins
        mv *.dll ../../../../Rocket/Libraries
        mv product.json ../../../../Rocket
        cd ../../../../Rocket
        zip -qr ./Release.zip *
        cd ..
      shell: bash
      
    - name: Zip OpenMod release artifacts
      run: |
        mkdir -p ./OpenMod/Plugins ./OpenMod/Libraries
        cd "./MovementModifier - OpenMod/bin/Release/net461"
        mv MovementModifier.dll ../../../../OpenMod/Plugins
        mv product.json ../../../../OpenMod
        cd ../../../../OpenMod
        zip -qr ./Release.zip *
        cd ..
      shell: bash
      
    - name: Upload Rocket release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Rocket/Release.zip
        asset_name: MovementModifier-Rocket-v${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip
        
    - name: Upload OpenMod release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OpenMod/Release.zip
        asset_name: MovementModifier-OpenMod-v${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip
